### ISSUE TITLE
Calculate 15/30 minute rolling average on headways

### ISSUE THREAD

**Issue by hamima-halim** [transitmatters/mbta-performance#20]
We'll also need to do something similar for scheduled headways. This is something the MBTA used to to for the v2 Performance API but not for LAMP, so it will smooth out the current metrics and also bring us to parity with the old version of the dashboard data.

**Comment by devinmatte** [comment]
Initial code for this exists in https://github.com/transitmatters/mbta-performance/pull/21. I am missing the last step of merging the calculated averages into the results, but it should offer a good base
